import { execFile } from "node:child_process";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, realpath, rename, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { CONFIG_DIR_NAME } from "@earendil-works/pi-coding-agent";
import { ContextRefreshLimiter, withDeadline } from "./context-state.js";

export const GIT_CONTEXT_COLLECTION_DEADLINE_MS = 2_000;
export const GIT_CONTEXT_REFRESH_INTERVAL_MS = 10_000;
export const GIT_CONTEXT_COMMIT_LIMIT = 10;
export const GIT_CONTEXT_FILE_LIMIT = 20;
export const GIT_CONTEXT_STATE_FILE_NAME = "pa-git-context.json";
const GIT_MAX_BUFFER_BYTES = 32 * 1024 * 1024;
const PERSISTED_STATE_VERSION = 1;

export type GitContextFailureKind =
  | "non-git"
  | "detached-head"
  | "unborn-head"
  | "missing-ref"
  | "missing-merge-base"
  | "git-error"
  | "timeout"
  | "unavailable";

export type GitReferenceSource = "explicit" | "saved" | "default" | "develop" | "origin-develop";
export type GitRefreshReason = "first-open" | "reference-change" | "event";

export interface GitBranch {
  /** Display name accepted by the selector, such as `develop` or `origin/develop`. */
  name: string;
  /** Fully qualified ref generated by enumeration, never from free-form user input. */
  fullName: `refs/heads/${string}` | `refs/remotes/${string}`;
  kind: "local" | "remote";
  current: boolean;
}

export interface GitCommitRow {
  hash: string;
  message: string;
  author: string;
  date: string;
}

export interface GitFileRow {
  /** New/current path, or the only path for a non-rename row. */
  path: string;
  oldPath?: string;
  /** Ready-to-render path; renames are represented as old → new. */
  displayPath: string;
  additions: number | null;
  deletions: number | null;
  binary: boolean;
}

export interface GitContextSnapshot {
  repositoryRoot: string;
  activeBranch: string;
  reference: GitBranch;
  referenceSource: GitReferenceSource;
  branches: GitBranch[];
  mergeBase: string;
  commits: GitCommitRow[];
  commitTotal: number;
  commitTruncated: number;
  files: GitFileRow[];
  fileTotal: number;
  fileTruncated: number;
  additions: number;
  deletions: number;
  collectedAt: number;
}

export interface GitContextReadyState {
  status: "ready";
  stale: false;
  snapshot: GitContextSnapshot;
}

export interface GitContextFailureState {
  status: GitContextFailureKind;
  stale: false;
  checkedAt: number;
  detail?: string;
}

export interface GitContextStaleState {
  status: "stale";
  stale: true;
  snapshot: GitContextSnapshot;
  cause: Extract<GitContextFailureKind, "git-error" | "timeout">;
  checkedAt: number;
  detail?: string;
}

export type GitContextState = GitContextReadyState | GitContextFailureState | GitContextStaleState;

export interface GitContextCollectionInput {
  cwd: string;
  /** A selector-provided branch name. It must exactly match an enumerated choice. */
  explicitReference?: string;
}

export type GitCommandRunner = (cwd: string, args: readonly string[], signal: AbortSignal) => Promise<string>;

export interface GitContextCollectorDependencies {
  runGit?: GitCommandRunner;
  canonicalize?: (path: string) => Promise<string>;
  loadReference?: (canonicalRepositoryRoot: string) => Promise<string | undefined>;
  now?: () => number;
  deadlineMs?: number;
  setTimer?: typeof setTimeout;
  clearTimer?: typeof clearTimeout;
}

export interface ResolvedGitReference {
  branch?: GitBranch;
  source?: GitReferenceSource;
  missingExplicit: boolean;
}

export interface PersistGitReferenceDependencies {
  mkdir?: typeof mkdir;
  writeFile?: typeof writeFile;
  rename?: typeof rename;
  rm?: typeof rm;
  uniqueId?: () => string;
}

interface EnumeratedRefs {
  branches: GitBranch[];
  detectedDefault?: string;
}

interface PersistedGitContext {
  version: typeof PERSISTED_STATE_VERSION;
  reference: string;
}

/**
 * Collect one committed-only Git comparison under one deadline. Runtime Git
 * commands are read-only and selector values are resolved back to enumerated
 * fully-qualified branch refs before they are passed to Git.
 */
export async function collectGitContext(
  previous: GitContextState | undefined,
  input: GitContextCollectionInput,
  dependencies: GitContextCollectorDependencies = {},
): Promise<GitContextState> {
  const controller = new AbortController();
  const deadlineMs = dependencies.deadlineMs ?? GIT_CONTEXT_COLLECTION_DEADLINE_MS;
  const timers = {
    setTimer: dependencies.setTimer ?? setTimeout,
    clearTimer: dependencies.clearTimer ?? clearTimeout,
  };
  const result = await withDeadline(
    () => collectGitContextAttempt(input, controller.signal, dependencies),
    deadlineMs,
    timers,
  );

  if (!result.ok) {
    if (result.timedOut) controller.abort();
    const kind: Extract<GitContextFailureKind, "git-error" | "timeout"> = result.timedOut ? "timeout" : "git-error";
    return staleOrFailure(previous, kind, dependencies.now ?? Date.now, result.error);
  }
  return result.value;
}

async function collectGitContextAttempt(
  input: GitContextCollectionInput,
  signal: AbortSignal,
  dependencies: GitContextCollectorDependencies,
): Promise<GitContextState> {
  const runGit = dependencies.runGit ?? runReadOnlyGit;
  const now = dependencies.now ?? Date.now;
  let topLevel: string;
  try {
    topLevel = requiredLine(await runGit(input.cwd, ["rev-parse", "--path-format=absolute", "--show-toplevel"], signal));
  } catch (error: unknown) {
    if (isNotGitRepository(error)) return failure("non-git", now(), error);
    throw error;
  }

  const repositoryRoot = await (dependencies.canonicalize ?? realpath)(topLevel);

  let activeBranch: string;
  try {
    await runGit(repositoryRoot, ["rev-parse", "--verify", "HEAD^{commit}"], signal);
  } catch (error: unknown) {
    try {
      activeBranch = requiredLine(await runGit(repositoryRoot, ["symbolic-ref", "--quiet", "--short", "HEAD"], signal));
      return failure("unborn-head", now(), error);
    } catch {
      throw error;
    }
  }
  try {
    activeBranch = requiredLine(await runGit(repositoryRoot, ["symbolic-ref", "--quiet", "--short", "HEAD"], signal));
  } catch (error: unknown) {
    return failure("detached-head", now(), error);
  }

  const refs = parseGitBranches(
    await runGit(
      repositoryRoot,
      ["for-each-ref", "--format=%(refname)%00%(symref)", "refs/heads", "refs/remotes"],
      signal,
    ),
    activeBranch,
  );
  const savedReference = input.explicitReference === undefined
    ? await (dependencies.loadReference ?? loadGitContextReference)(repositoryRoot)
    : undefined;
  const resolved = resolveGitReference(refs.branches, {
    explicitReference: input.explicitReference,
    savedReference,
    detectedDefault: refs.detectedDefault,
  });
  if (resolved.missingExplicit) return failure("missing-ref", now(), input.explicitReference);
  if (!resolved.branch || !resolved.source) return failure("unavailable", now());

  let mergeBase: string;
  try {
    mergeBase = requiredObjectId(
      await runGit(repositoryRoot, ["merge-base", resolved.branch.fullName, "HEAD"], signal),
    );
  } catch (error: unknown) {
    if (isMissingMergeBase(error)) return failure("missing-merge-base", now(), error);
    throw error;
  }
  const range = `${mergeBase}..HEAD`;

  const commitTotal = parseCount(
    await runGit(repositoryRoot, ["rev-list", "--count", range], signal),
    "commit count",
  );
  const commits = parseGitLog(
    await runGit(
      repositoryRoot,
      ["log", "-z", `--max-count=${GIT_CONTEXT_COMMIT_LIMIT}`, "--format=%h%x00%s%x00%an%x00%aI", range],
      signal,
    ),
  );
  const parsedFiles = parseGitNumstat(
    await runGit(repositoryRoot, ["diff", "--numstat", "-z", "--find-renames", range, "--"], signal),
  );
  const orderedFiles = [...parsedFiles].sort(compareFileRows);
  const additions = parsedFiles.reduce((total, file) => total + (file.additions ?? 0), 0);
  const deletions = parsedFiles.reduce((total, file) => total + (file.deletions ?? 0), 0);

  return {
    status: "ready",
    stale: false,
    snapshot: {
      repositoryRoot,
      activeBranch,
      reference: resolved.branch,
      referenceSource: resolved.source,
      branches: refs.branches,
      mergeBase,
      commits: commits.slice(0, GIT_CONTEXT_COMMIT_LIMIT),
      commitTotal,
      commitTruncated: Math.max(0, commitTotal - commits.length),
      files: orderedFiles.slice(0, GIT_CONTEXT_FILE_LIMIT),
      fileTotal: parsedFiles.length,
      fileTruncated: Math.max(0, parsedFiles.length - GIT_CONTEXT_FILE_LIMIT),
      additions,
      deletions,
      collectedAt: now(),
    },
  };
}

/** Parse only local and locally present remote-tracking refs. Symbolic refs are omitted as choices. */
export function parseGitBranches(output: string, activeBranch?: string): EnumeratedRefs {
  const branches: GitBranch[] = [];
  const symbolicDefaults: Array<{ alias: string; target: string }> = [];
  for (const rawLine of output.split("\n")) {
    const line = rawLine.endsWith("\r") ? rawLine.slice(0, -1) : rawLine;
    if (!line) continue;
    const separator = line.indexOf("\0");
    if (separator < 0) throw new Error("Invalid NUL-delimited branch record.");
    const fullName = line.slice(0, separator);
    const symbolicTarget = line.slice(separator + 1);
    if (symbolicTarget) {
      if (fullName.startsWith("refs/remotes/") && fullName.endsWith("/HEAD")) {
        symbolicDefaults.push({ alias: fullName, target: symbolicTarget });
      }
      continue;
    }
    const branch = branchFromFullName(fullName, activeBranch);
    if (branch) branches.push(branch);
  }
  branches.sort((left, right) => left.kind === right.kind ? compareText(left.name, right.name) : left.kind === "local" ? -1 : 1);
  symbolicDefaults.sort((left, right) => {
    const leftOrigin = left.alias === "refs/remotes/origin/HEAD" ? 0 : 1;
    const rightOrigin = right.alias === "refs/remotes/origin/HEAD" ? 0 : 1;
    return leftOrigin - rightOrigin || compareText(left.alias, right.alias);
  });
  const detectedDefault = symbolicDefaults
    .map(({ target }) => branches.find((branch) => branch.fullName === target)?.name)
    .find((name): name is string => name !== undefined);
  return { branches, detectedDefault };
}

export function resolveGitReference(
  branches: readonly GitBranch[],
  input: { explicitReference?: string; savedReference?: string; detectedDefault?: string },
): ResolvedGitReference {
  const find = (name: string | undefined) => name === undefined ? undefined : branches.find((branch) => branch.name === name);
  if (input.explicitReference !== undefined) {
    const branch = find(input.explicitReference);
    return { branch, source: branch ? "explicit" : undefined, missingExplicit: !branch };
  }
  const saved = find(input.savedReference);
  if (saved) return { branch: saved, source: "saved", missingExplicit: false };
  const detected = find(input.detectedDefault);
  if (detected) return { branch: detected, source: "default", missingExplicit: false };
  const develop = find("develop");
  if (develop) return { branch: develop, source: "develop", missingExplicit: false };
  const originDevelop = find("origin/develop");
  if (originDevelop) return { branch: originDevelop, source: "origin-develop", missingExplicit: false };
  return { missingExplicit: false };
}

export function parseGitLog(output: string): GitCommitRow[] {
  if (!output) return [];
  const fields = output.split("\0");
  if (fields.at(-1) === "") fields.pop();
  if (fields.length % 4 !== 0) throw new Error("Invalid NUL-delimited Git log output.");
  const commits: GitCommitRow[] = [];
  for (let index = 0; index < fields.length; index += 4) {
    commits.push({
      hash: fields[index]!,
      message: fields[index + 1]!,
      author: fields[index + 2]!,
      date: fields[index + 3]!,
    });
  }
  return commits;
}

/** Parse `git diff --numstat -z`, including its three-token rename representation. */
export function parseGitNumstat(output: string): GitFileRow[] {
  if (!output) return [];
  const tokens = output.split("\0");
  if (tokens.at(-1) === "") tokens.pop();
  const rows: GitFileRow[] = [];
  for (let index = 0; index < tokens.length;) {
    const header = tokens[index++]!;
    const firstTab = header.indexOf("\t");
    const secondTab = header.indexOf("\t", firstTab + 1);
    if (firstTab < 0 || secondTab < 0) throw new Error("Invalid NUL-delimited numstat record.");
    const additionsText = header.slice(0, firstTab);
    const deletionsText = header.slice(firstTab + 1, secondTab);
    const inlinePath = header.slice(secondTab + 1);
    const binary = additionsText === "-" || deletionsText === "-";
    const additions = binary ? null : parseNumstatCount(additionsText);
    const deletions = binary ? null : parseNumstatCount(deletionsText);
    if (inlinePath) {
      rows.push({ path: inlinePath, displayPath: inlinePath, additions, deletions, binary });
      continue;
    }
    const oldPath = tokens[index++];
    const newPath = tokens[index++];
    if (oldPath === undefined || newPath === undefined || oldPath === "" || newPath === "") {
      throw new Error("Invalid NUL-delimited rename numstat record.");
    }
    rows.push({ path: newPath, oldPath, displayPath: `${oldPath} → ${newPath}`, additions, deletions, binary });
  }
  return rows;
}

export function gitContextStatePath(canonicalRepositoryRoot: string): string {
  return join(canonicalRepositoryRoot, CONFIG_DIR_NAME, GIT_CONTEXT_STATE_FILE_NAME);
}

/** Missing or malformed state is intentionally ignored. */
export async function loadGitContextReference(canonicalRepositoryRoot: string): Promise<string | undefined> {
  try {
    const parsed = JSON.parse(await readFile(gitContextStatePath(canonicalRepositoryRoot), "utf8")) as unknown;
    if (!isPersistedGitContext(parsed)) return undefined;
    return parsed.reference;
  } catch {
    return undefined;
  }
}

/**
 * Persist only an exact enumerated branch choice. The temp file is in the same
 * project-local config directory so successful rename is an atomic replacement.
 */
export async function persistGitContextReference(
  canonicalRepositoryRoot: string,
  reference: string,
  branches: readonly GitBranch[],
  dependencies: PersistGitReferenceDependencies = {},
): Promise<boolean> {
  if (!branches.some((branch) => branch.name === reference)) return false;
  const statePath = gitContextStatePath(canonicalRepositoryRoot);
  const configDirectory = join(canonicalRepositoryRoot, CONFIG_DIR_NAME);
  const uniqueId = dependencies.uniqueId?.() ?? `${process.pid}-${randomUUID()}`;
  const tempPath = join(configDirectory, `.${GIT_CONTEXT_STATE_FILE_NAME}.${uniqueId}.tmp`);
  const value: PersistedGitContext = { version: PERSISTED_STATE_VERSION, reference };
  const mkdirImpl = dependencies.mkdir ?? mkdir;
  const writeFileImpl = dependencies.writeFile ?? writeFile;
  const renameImpl = dependencies.rename ?? rename;
  const rmImpl = dependencies.rm ?? rm;
  try {
    await mkdirImpl(configDirectory, { recursive: true });
    await writeFileImpl(tempPath, `${JSON.stringify(value, null, 2)}\n`, { encoding: "utf8", flag: "wx", mode: 0o600 });
    await renameImpl(tempPath, statePath);
    return true;
  } catch {
    try {
      await rmImpl(tempPath, { force: true });
    } catch {
      // Cleanup failure does not make extension startup or selection fail noisily.
    }
    return false;
  }
}

/** Phase 2 wires these hooks to overlay/session events. */
export class GitContextRefreshScheduler {
  private readonly limiter: ContextRefreshLimiter;

  constructor(
    intervalMs = GIT_CONTEXT_REFRESH_INTERVAL_MS,
    now: () => number = Date.now,
    setTimer: typeof setTimeout = setTimeout,
    clearTimer: typeof clearTimeout = clearTimeout,
  ) {
    this.limiter = new ContextRefreshLimiter(intervalMs, now, setTimer, clearTimer);
  }

  firstOpen(refresh: (reason: GitRefreshReason) => void | Promise<void>): void {
    this.request("first-open", refresh);
  }

  referenceChange(refresh: (reason: GitRefreshReason) => void | Promise<void>): void {
    this.request("reference-change", refresh);
  }

  event(refresh: (reason: GitRefreshReason) => void | Promise<void>): void {
    this.request("event", refresh);
  }

  dispose(): void {
    this.limiter.dispose();
  }

  private request(reason: GitRefreshReason, refresh: (reason: GitRefreshReason) => void | Promise<void>): void {
    this.limiter.request(() => refresh(reason));
  }
}

function branchFromFullName(fullName: string, activeBranch?: string): GitBranch | undefined {
  if (fullName.startsWith("refs/heads/")) {
    const name = fullName.slice("refs/heads/".length);
    if (!name) return undefined;
    return { name, fullName: `refs/heads/${name}`, kind: "local", current: name === activeBranch };
  }
  if (fullName.startsWith("refs/remotes/")) {
    const name = fullName.slice("refs/remotes/".length);
    if (!name || name.endsWith("/HEAD")) return undefined;
    return { name, fullName: `refs/remotes/${name}`, kind: "remote", current: false };
  }
  return undefined;
}

function staleOrFailure(
  previous: GitContextState | undefined,
  kind: Extract<GitContextFailureKind, "git-error" | "timeout">,
  now: () => number,
  error?: unknown,
): GitContextState {
  const snapshot = previous?.status === "ready" || previous?.status === "stale" ? previous.snapshot : undefined;
  const detail = errorDetail(error);
  if (snapshot) return { status: "stale", stale: true, snapshot, cause: kind, checkedAt: now(), ...(detail ? { detail } : {}) };
  return { status: kind, stale: false, checkedAt: now(), ...(detail ? { detail } : {}) };
}

function failure(status: GitContextFailureKind, checkedAt: number, detailValue?: unknown): GitContextFailureState {
  const detail = typeof detailValue === "string" ? detailValue : errorDetail(detailValue);
  return { status, stale: false, checkedAt, ...(detail ? { detail } : {}) };
}

function isPersistedGitContext(value: unknown): value is PersistedGitContext {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const record = value as Record<string, unknown>;
  return record.version === PERSISTED_STATE_VERSION && typeof record.reference === "string" && record.reference.length > 0;
}

function requiredLine(output: string): string {
  const value = output.replace(/[\r\n]+$/, "");
  if (!value) throw new Error("Git returned an empty value.");
  return value;
}

function requiredObjectId(output: string): string {
  const value = requiredLine(output);
  if (!/^[0-9a-fA-F]{40,64}$/.test(value)) throw new Error("Git returned an invalid object ID.");
  return value;
}

function parseCount(output: string, label: string): number {
  const value = requiredLine(output);
  if (!/^\d+$/.test(value)) throw new Error(`Git returned an invalid ${label}.`);
  return Number(value);
}

function parseNumstatCount(value: string): number {
  if (!/^\d+$/.test(value)) throw new Error("Git returned an invalid numstat count.");
  return Number(value);
}

function compareFileRows(left: GitFileRow, right: GitFileRow): number {
  return compareText(`${left.oldPath ?? ""}\0${left.path}`, `${right.oldPath ?? ""}\0${right.path}`);
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function errorDetail(error: unknown): string | undefined {
  if (error instanceof GitCommandError) return (error.stderr || error.message).trim().slice(0, 500) || undefined;
  if (error instanceof Error) return error.message.trim().slice(0, 500) || undefined;
  return typeof error === "string" ? error.trim().slice(0, 500) || undefined : undefined;
}

function isNotGitRepository(error: unknown): boolean {
  const detail = error instanceof GitCommandError ? `${error.stderr}\n${error.message}` : error instanceof Error ? error.message : String(error);
  return /not a git repository|not a git work tree/i.test(detail);
}

function isMissingMergeBase(error: unknown): boolean {
  if (error instanceof GitCommandError) return error.exitCode === 1;
  return error instanceof Error && /no merge base/i.test(error.message);
}

class GitCommandError extends Error {
  readonly exitCode: number | undefined;

  constructor(
    readonly args: readonly string[],
    readonly stderr: string,
    readonly causeValue?: unknown,
  ) {
    super(`Read-only Git command failed: git ${args.join(" ")}`);
    this.name = "GitCommandError";
    const code = causeValue && typeof causeValue === "object" && "code" in causeValue
      ? causeValue.code
      : undefined;
    this.exitCode = typeof code === "number" ? code : undefined;
  }
}

function runReadOnlyGit(cwd: string, args: readonly string[], signal: AbortSignal): Promise<string> {
  return new Promise((resolve, reject) => {
    execFile(
      "git",
      ["-C", cwd, ...args],
      { encoding: "utf8", maxBuffer: GIT_MAX_BUFFER_BYTES, signal, windowsHide: true },
      (error, stdout, stderr) => {
        if (error) {
          reject(new GitCommandError(args, stderr, error));
          return;
        }
        resolve(stdout);
      },
    );
  });
}
